export const manualSections=[
 {title:'Cover & contents',page:1,label:'Front matter'},
 {title:'Model codes & configuration',page:6,label:'Fig. 2 · iv'},
 {title:'Introduction & performance',page:7,label:'§1 · p. 1'},
 {title:'Piping & system design',page:9,label:'§2 · p. 3'},
 {title:'Drive & lubrication',page:13,label:'§3 · p. 7'},
 {title:'Drive reassembly',page:14,label:'§3.4 · p. 8'},
 {title:'HPD liquid end',page:17,label:'§4 · p. 11'},
 {title:'Start-up & relief valve',page:18,label:'§4.3 · p. 12'},
 {title:'Maintenance & RPM kits',page:19,label:'§4.4 · p. 13'},
 {title:'Check valve service',page:20,label:'§4.4.3 · p. 14'},
 {title:'MARS & piston assemblies',page:21,label:'§4.4.5–6 · p. 15'},
 {title:'Troubleshooting',page:23,label:'§5 · p. 17'},
 {title:'Parts list guide',page:25,label:'§6 · p. 19'},
 {title:'Simplex drive drawing',page:26,label:'Fig. 8 · p. 20'},
 {title:'Simplex drive parts',page:27,label:'§6.3 · p. 21'},
 {title:'Duplex drive drawing',page:30,label:'Fig. 9 · p. 24'},
 {title:'Metallic liquid-end parts',page:33,label:'§6.5 · p. 28'},
 {title:'Metallic liquid-end drawing',page:40,label:'Fig. 10 · p. 27'},
 {title:'Plastic liquid-end drawing',page:38,label:'Fig. 11 · p. 33'},
 {title:'3½″ metallic liquid end',page:44,label:'Fig. 12 · p. 38'},
 {title:'3½″ plastic liquid end',page:48,label:'Fig. 13 · p. 42'},
 {title:'Relief valve assembly',page:51,label:'Fig. 14 · p. 45'},
];
export const maintenanceTopics=[
 {id:'lubrication',title:'Drive lubrication',frequency:'6 months / 3,000 hours',summary:'Change the drive lubricant at whichever limit comes first. The hydraulic oil follows the same inspection and replacement schedule.',details:['Section 3.2 specifies Mobil Gear 629 or Mobil SHC 629 for ambient temperatures of 40°F–140°F; consult the factory for other temperatures.','The manual gives approximately 5 US gallons for the combined drive and liquid end. Section 4.4.2 separately describes approximately 1 gallon (4 L) for the hydraulic liquid end; do not treat that as the whole-pump capacity.'],page:13,reference:'§3.2 · p. 7; §4.4.2 · p. 13',parts:['housing','sight','breather']},
 {id:'rpm',title:'Preventive maintenance kit',frequency:'Configuration specific',summary:'For the illustrated 1-inch, 316SS liquid end (CBH-161), Table 2 lists RPM-0011-021.',details:['The metallic kit contents listed in the manual are 2 seats, 2 ball checks, 1 hydraulic fluid strainer, and 10 gaskets.','Confirm the pump model, plunger size, material and valve arrangement before choosing a kit. Duplex HPD and metallic double-ball arrangements require two kits according to §4.4.1.','The manual recommends periodic replacement components but does not give a universal kit replacement interval.'],page:19,reference:'§4.4.1 & Table 2 · pp. 13–14',parts:['balls','valvegasket','guide']},
 {id:'checks',title:'Check valves & gaskets',frequency:'During valve service',summary:'Inspect check balls, seats and sealing grooves; replace the gaskets after disassembly.',details:['Balls should be smooth, round, and free of deposits or pits. The manual rejects seats with pits, erosion, cracks, or a ball-matching contour deeper than 0.030 inch.','Replace parts with damaged sealing grooves. Use a new gasket between each pair of cleaned mating components.','Use the correct assembly drawing and the complete reassembly procedure; valve arrangement and fasteners vary by liquid end.'],page:20,reference:'§4.4.3 · p. 14',parts:['balls','guide','valvegasket','ports']},
 {id:'relief',title:'Hydraulic relief valve',frequency:'Inspect / clean as needed',summary:'Routine maintenance is generally unnecessary when the valve operates in clean, filtered hydraulic oil.',details:['Field service is limited to inspection and cleaning. The manual directs further repair of this critical component to an authorized Milton Roy repair facility.','Never set the valve above the limit stated in §4.3.4. Consult the complete pressure-setting procedure rather than using the teaching model as an adjustment guide.'],page:20,reference:'§4.4.4 · pp. 14–15; §4.3.4 · p. 12',parts:['relief']},
 {id:'mars',title:'MARS refill valve',frequency:'No periodic service specified',summary:'Clean hydraulic oil is critical to the refill valve’s operation.',details:['Section 4.4.5 states that no periodic maintenance is required.','If the valve is removed, follow the complete removal instructions. Do not pry the large poppet. Reinstallation requires new O-rings and backup rings.'],page:21,reference:'§4.4.5 · p. 15',parts:['mars','chamber']},
 {id:'drive',title:'Drive assembly service',frequency:'When repair is required',summary:'Use the drive disassembly and reassembly procedures for bearing, shaft and crosshead work.',details:['Disconnect electrical power before disassembly. The manual identifies the main shaft and gear assembly as approximately 45 lb (20 kg); it requires support during removal.','Special shim packs are required for the upper bearing cap and motor mounting components. Follow §3.4 for shaft end-play checks and assembly requirements.'],page:13,reference:'§3.3–3.4 · pp. 7–10',parts:['gear','yoke','bearing','upper']},
];
export const troubleGroups=[
 {id:'excessive',title:'Excessive delivery',description:'The pump delivers more liquid than expected.',checks:[{cause:'Discharge pressure too low',action:'The manual says discharge pressure must exceed suction pressure by more than 10 psi. Evaluate backpressure; a back-pressure valve is given as one corrective option.',parts:['ports'],page:23}]},
 {id:'insufficient',title:'Insufficient delivery',description:'The pump delivers less liquid than expected.',checks:[
  {cause:'Blocked discharge line',action:'Inspect the discharge path for blockage. Isolate and depressurize before clearing the line.',parts:['ports'],page:23},
  {cause:'Relief valve setting too low',action:'Check the setting against operating conditions and the full §4.3.4 procedure. Do not exceed the specified relief-pressure limit.',parts:['relief'],page:18},
  {cause:'Air in the hydraulic system',action:'The manual directs filling the displacement chamber with hydraulic oil to the proper level. See §4.3.2 for the applicable filling procedure and prerequisites.',parts:['chamber'],page:18},
  {cause:'Clogged refill line',action:'Inspect and clean the strainer assembly as directed by the troubleshooting guide.',parts:['mars'],page:23},
  {cause:'Restricted suction line',action:'Check for a suction blockage or undersized piping; the manual lists clearing the blockage and/or increasing pipe size.',parts:['ports'],page:23},
  {cause:'Insufficient NPSH',action:'Analyze the suction system for adequate net positive suction head. Review the piping and liquid-end installation sections.',parts:['head'],page:17},
 ]},
 {id:'erratic',title:'Erratic delivery',description:'The delivery rate varies unexpectedly.',checks:[{cause:'Leaking relief valve',action:'Section 5 lists repair or replacement of a leaking relief valve. Section 4.4.4 limits field service to inspection and cleaning and directs further repair to an authorized Milton Roy facility.',parts:['relief'],page:20}]},
];
