import { useState } from 'react';
import { ArrowRight, BookOpen, Box, Clock3, Droplets, Search, ShieldCheck, Wrench } from 'lucide-react';
import { maintenanceTopics, troubleGroups } from './manual-content';
import { byId } from './parts';
import './model.css';

type Props = { onManual: (page: number) => void; onPart: (id: string) => void };
function ServiceContext({ onManual }: Pick<Props, 'onManual'>) {
  return <div className="service-context"><ShieldCheck size={20} /><p><b>Before service</b> Disconnect electrical power before disassembly. Relieve system pressure, isolate the liquid end and purge process liquid before maintenance. Follow the full manual procedure for the installed configuration.</p><button onClick={() => onManual(19)}>Read precautions <ArrowRight size={13} /></button></div>;
}
function PartLinks({ ids, onPart }: { ids: string[]; onPart: Props['onPart'] }) {
  return <div className="service-parts">{ids.map(id => <button key={id} onClick={() => onPart(id)}><Box size={12} />{byId[id]?.name ?? id}<ArrowRight size={11} /></button>)}</div>;
}
export function MaintenanceGuide({ onManual, onPart }: Props) {
  return <div className="service-page"><div className="service-hero"><div><span className="eyebrow">CARE / MANUAL REFERENCE</span><h1>Maintenance, in context.</h1><p>Intervals, inspection points and component links from your Centrac B manual.</p></div><button onClick={() => onManual(19)}><BookOpen size={15} />Read maintenance section</button></div><ServiceContext onManual={onManual} /><div className="service-highlights"><div><Clock3 /><span>LUBRICANT CHANGE<b>6 months / 3,000 hours</b><small>Whichever comes first · §3.2</small></span></div><div><Wrench /><span>ILLUSTRATED CONFIGURATION KIT<b>RPM-0011-021</b><small>1″ · 316SS · CBH-161 · Table 2</small></span></div><div><Droplets /><span>HYDRAULIC OIL<b>Same service schedule</b><small>Inspect and replace with drive lubricant · §4.4.2</small></span></div></div><div className="service-layout"><div className="maintenance-cards">{maintenanceTopics.map(t => <article className="maintenance-card" key={t.id}><div className="topic-top"><Wrench size={15} /><span>{t.frequency}</span></div><h2>{t.title}</h2><p>{t.summary}</p><ul>{t.details.map(d => <li key={d}>{d}</li>)}</ul><PartLinks ids={t.parts} onPart={onPart} /><button className="source-page-button" onClick={() => onManual(t.page)}><BookOpen size={13} />{t.reference}<ArrowRight size={12} /></button></article>)}</div><aside className="service-aside"><span className="eyebrow">ABOUT THIS GUIDE</span><h3>A quick route to the source.</h3><p>These are reading notes from the supplied IOM, not a replacement for its complete procedures.</p><p>Part and kit applicability depends on the actual pump’s model, materials, plunger size and valve configuration.</p><button onClick={() => onManual(6)}>Model code reference <ArrowRight size={12} /></button></aside></div></div>;
}

export function TroubleshootingGuide({ onManual, onPart }: Props) {
  const [symptom, setSymptom] = useState('insufficient'), [query, setQuery] = useState('');
  const group = troubleGroups.find(g => g.id === symptom)!;
  const visible = group.checks.filter(c => `${c.cause} ${c.action}`.toLowerCase().includes(query.toLowerCase()));
  return <div className="service-page"><div className="service-hero"><div><span className="eyebrow">DIAGNOSE / SECTION 5</span><h1>Start with the symptom.</h1><p>Possible causes from the manual—not an automatic diagnosis.</p></div><button onClick={() => onManual(23)}><BookOpen size={15} />Read troubleshooting page</button></div><ServiceContext onManual={onManual} /><div className="trouble-layout"><aside className="symptom-list"><span className="eyebrow">DELIVERY SYMPTOM</span>{troubleGroups.map(g => <button key={g.id} aria-pressed={symptom === g.id} className={symptom === g.id ? 'active' : ''} onClick={() => { setSymptom(g.id); setQuery('') }}><span><b>{g.title}</b><small>{g.checks.length} possible {g.checks.length === 1 ? 'cause' : 'causes'}</small></span><ArrowRight size={15} /></button>)}</aside><section className="trouble-results"><div className="trouble-heading"><div><h2>{group.title}</h2><p>{group.description}</p></div><div className="trouble-search"><Search size={15} /><input aria-label="Filter possible causes" placeholder="Filter causes…" value={query} onChange={e => setQuery(e.target.value)} /></div></div>{visible.length ? <div key={symptom + query} className="cause-accordion">{visible.map((c, i) => <details className="cause-item" key={c.cause} open={i === 0}><summary className="cause-trigger"><span className="cause-number">{String(i + 1).padStart(2, '0')}</span><span>{c.cause}</span></summary><div className="cause-body"><p>{c.action}</p><PartLinks ids={c.parts} onPart={onPart} /><button className="source-page-button" onClick={() => onManual(c.page)}><BookOpen size={13} />Read supporting procedure<ArrowRight size={12} /></button></div></details>)}</div> : <p className="empty">No matching causes for this symptom.</p>}<div className="trouble-source"><BookOpen size={16} /><p><b>Source: Section 5, printed page 17</b>Six insufficient-delivery causes, one excessive-delivery cause and one erratic-delivery cause are listed in the supplied manual. Linked procedures provide the surrounding maintenance requirements.</p><button onClick={() => onManual(23)}>Read source <ArrowRight size={12} /></button></div></section></div></div>;
}
